# Use the nginx docker image.
FROM mysql:latest

# Set the mysql environment variables.
ENV MYSQL_ROOT_PASSWORD=mysql_pass
ENV MYSQL_DATABASE=mysql_database_name
ENV MYSQL_USER=michael
ENV MYSQL_PASSWORD=password

# Expose port 3306 so it is accessible from outside the container.
EXPOSE 3306